export const products = [
	{
		id: '1',
		name: 'T-shirt with Tape Details',
		desc: 'This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.',
		fullPrice: '',
		price: '$ 120',
		discount: '',
		rating: 4.5,
		img: './img/arrivals_selling/img_1.jpg',
		colors: ['black', 'green', 'blue', 'maroon', 'yellow', 'brown', 'purple', 'orange'],
		sizes: ['Small', 'Medium', 'Large', 'X-Large'],
	},
	{
		id: '2',
		name: 'Skinny Fit Jeans',
		desc: 'These skinny fit jeans are a timeless wardrobe essential, perfect for everyday wear or a night out. Made from stretchable and durable denim, they offer a sleek silhouette without compromising on comfort.',
		fullPrice: '$ 260',
		price: '$ 240',
		discount: '-20%',
		rating: 3.5,
		img: './img/arrivals_selling/img_2.jpg',
		colors: ['black', 'blue', 'brown'],
		sizes: ['Small', 'Medium', 'Large', 'X-Large'],
	},
	{
		id: '3',
		name: 'Checked Shirt',
		desc: 'This checked shirt combines classic design with modern comfort, making it ideal for both casual and semi-formal occasions. Crafted from soft cotton fabric, it ensures breathability and effortless style throughout the day.',
		fullPrice: '',
		price: '$ 180',
		discount: '',
		rating: 4.5,
		img: './img/arrivals_selling/img_3.jpg',
		colors: ['black', 'blue', 'brown', 'maroon'],
		sizes: ['Small', 'Medium', 'Large', 'X-Large'],
	},
	{
		id: '4',
		name: 'Sleeve Striped T-shirt',
		desc: 'This sleeve striped t-shirt adds a sporty touch to your everyday look. Designed with breathable fabric and a relaxed fit, it offers all-day comfort and a modern, casual vibe.',
		fullPrice: '$ 160',
		price: '$ 130',
		discount: '-30%',
		rating: 4.5,
		img: './img/arrivals_selling/img_4.jpg',
		colors: ['black', 'brown', 'orange'],
		sizes: ['Small', 'Medium', 'Large', 'X-Large'],
	},
	{
		id: '5',
		name: 'Verrtical Striped Shirt',
		desc: 'This vertical striped shirt offers a clean, elongated look with lightweight fabric and versatile style for any setting.',
		fullPrice: '$ 232',
		price: '$ 212',
		discount: '-20%',
		rating: 3.5,
		img: './img/arrivals_selling/img_5.jpg',
		colors: ['green', 'blue'],
		sizes: ['Small', 'Medium', 'Large', 'X-Large'],
	},
	{
		id: '6',
		name: 'Courage Graphic',
		desc: 'This graphic t-shirt features a bold "Courage" print, combining statement style with soft, breathable comfort',
		fullPrice: '',
		price: '$ 145',
		discount: '',
		rating: 4.5,
		img: './img/arrivals_selling/img_6.jpg',
		colors: ['orange', 'yellow'],
		sizes: ['Small', 'Medium', 'Large', 'X-Large'],
	},
	{
		id: '7',
		name: 'Loose Fit Bermuda Shorts',
		desc: 'These loose fit Bermuda shorts offer relaxed comfort and a casual look, perfect for warm-weather days.',
		fullPrice: '',
		price: '$ 80',
		discount: '',
		rating: 4.0,
		img: './img/arrivals_selling/img_7.jpg',
		colors: ['black', 'green', 'blue'],
		sizes: ['Small', 'Medium', 'Large', 'X-Large'],
	},
	{
		id: '8',
		name: 'Faded Skinny Jeans',
		desc: 'These faded skinny jeans deliver a sleek fit with a worn-in look, blending comfort and urban edge.',
		fullPrice: '242',
		price: '$ 210',
		discount: '-20%',
		rating: 4.5,
		img: './img/arrivals_selling/img_8.jpg',
		colors: ['black', 'blue', 'brown'],
		sizes: ['Small', 'Medium', 'Large', 'X-Large'],
	},
];
